# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 56a8e40ecd9631edbe4a8e75ca58873fd52faeeba303b9b5f78721918e7a736ac163b2648078c7fb750029d60a93dabd0867cdde9ababd36c18eea8972f8dac1

test:
  secret_key_base: 65b47cb81de04a555dea2d379e6f81c87aae6a3366444a13965b035565ab247d62300148b32539efb695773290259fa8dfa5ac68dccc4ef9b41ecf80623b525d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
